### ISSUE TITLE
How to read the generated pt files

### ISSUE THREAD

**Issue by phongnhhn92** [iShohei220/torch-gqn#4]
Hello, I have used the convert2Torch.py script to generate all pt.gz files.
I would like to ask how to save input images from a "Scene" on the file 0.pt ?

**Comment by jaks19** [comment]
Hi I believe you can read them using pytorch Dataset and Dataloader classes. See gqn_dataset.py for an example. (https://github.com/iShohei220/torch-gqn/blob/master/gqn_dataset.py)

**Comment by phongnhhn92** [comment]
Also, I would like to ask, is there any specific reason why in the script convert2torch.py, why he has to save the compressed input as pt.gz instead of .pt ? 
https://github.com/iShohei220/torch-gqn/blob/c0156c72f4e63ca6523ab8d9a6f6b3ce9e0e391d/dataset/convert2torch.py#L179
I just make a simple change in the function of convert_raw_to_numpy() that remove the gzip part and just let torch save the tensor as pt file. Is that ok to do so ? 
```
#with gzip.open(path, 'wb') as f:
torch.save(scene, f)
```
